services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./app
    # command: python manage.py runserver 127.0.0.1:8000
    # volumes:
    #   - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: